#!/bin/sh

set -e

while :; do
	set +e
	output=$(kimsufi availability "${1:-2201sk011}")
	status=$?
	set -e

	if [ $status -ne 0 ]; then
		echo "$(date -Iseconds) Error"
		sleep 1m
	elif [ "$output" = "unavailable" ]; then
		echo "$(date -Iseconds) Unavailable"
		sleep 1m
	else
		echo "$(date -Iseconds) Available"
		ntfy -t Kimsufi -m "Server available: $output"
		sleep 30m
	fi
done
